#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-checkstyle
Version  : 6.18
Release  : 4
URL      : https://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/6.18/checkstyle-6.18.jar
Source0  : https://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/6.18/checkstyle-6.18.jar
Source1  : https://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/6.1.1/checkstyle-6.1.1.jar
Source2  : https://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/6.1.1/checkstyle-6.1.1.pom
Source3  : https://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/6.18/checkstyle-6.18.pom
Source4  : https://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/6.19/checkstyle-6.19.jar
Source5  : https://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/6.19/checkstyle-6.19.pom
Source6  : https://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/8.12/checkstyle-8.12.jar
Source7  : https://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/8.12/checkstyle-8.12.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: mvn-checkstyle-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-checkstyle package.
Group: Data

%description data
data components for the mvn-checkstyle package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/puppycrawl/tools/checkstyle/6.18
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/com/puppycrawl/tools/checkstyle/6.18/checkstyle-6.18.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/puppycrawl/tools/checkstyle/6.1.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/puppycrawl/tools/checkstyle/6.1.1/checkstyle-6.1.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/puppycrawl/tools/checkstyle/6.1.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/puppycrawl/tools/checkstyle/6.1.1/checkstyle-6.1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/puppycrawl/tools/checkstyle/6.18
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/puppycrawl/tools/checkstyle/6.18/checkstyle-6.18.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/puppycrawl/tools/checkstyle/6.19
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/com/puppycrawl/tools/checkstyle/6.19/checkstyle-6.19.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/puppycrawl/tools/checkstyle/6.19
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/com/puppycrawl/tools/checkstyle/6.19/checkstyle-6.19.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/puppycrawl/tools/checkstyle/8.12
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/com/puppycrawl/tools/checkstyle/8.12/checkstyle-8.12.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/puppycrawl/tools/checkstyle/8.12
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/com/puppycrawl/tools/checkstyle/8.12/checkstyle-8.12.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/puppycrawl/tools/checkstyle/6.1.1/checkstyle-6.1.1.jar
/usr/share/java/.m2/repository/com/puppycrawl/tools/checkstyle/6.1.1/checkstyle-6.1.1.pom
/usr/share/java/.m2/repository/com/puppycrawl/tools/checkstyle/6.18/checkstyle-6.18.jar
/usr/share/java/.m2/repository/com/puppycrawl/tools/checkstyle/6.18/checkstyle-6.18.pom
/usr/share/java/.m2/repository/com/puppycrawl/tools/checkstyle/6.19/checkstyle-6.19.jar
/usr/share/java/.m2/repository/com/puppycrawl/tools/checkstyle/6.19/checkstyle-6.19.pom
/usr/share/java/.m2/repository/com/puppycrawl/tools/checkstyle/8.12/checkstyle-8.12.jar
/usr/share/java/.m2/repository/com/puppycrawl/tools/checkstyle/8.12/checkstyle-8.12.pom
